name: Publish Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - registryName: npm
            registryUrl: 'https://registry.npmjs.org/'
            access: 'public'
          - registryName: github
            registryUrl: 'https://npm.pkg.github.com/'
            access: ''

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.9.0
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build package
        run: pnpm run build

      # Generate .npmrc dynamically for npm registry
      - name: Generate .npmrc dynamically
        if: matrix.registryName == 'npm'
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Generate .npmrc dynamically for GitHub registry
      - name: Generate .npmrc dynamically (GitHub)
        if: matrix.registryName == 'github'
        run: |
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if package version already published
        id: version-check
        run: |
          PKG_NAME=$(node -p "require('./package.json').name")
          PKG_VERSION=$(node -p "require('./package.json').version")

          echo "Checking $PKG_NAME@$PKG_VERSION on ${{ matrix.registryUrl }}"

          if npm view "$PKG_NAME@$PKG_VERSION" --registry=${{ matrix.registryUrl }} > /dev/null 2>&1; then
            echo "Already published!"
            echo "published=true" >> $GITHUB_ENV
          else
            echo "Not yet published."
            echo "published=false" >> $GITHUB_ENV
          fi

      # Publish to npm registry if not already published
      - name: Publish package
        if: env.published == 'false' && matrix.registryName == 'npm'
        run: |
          echo "Publishing to ${{ matrix.registryName }}..."
          npm publish --registry=${{ matrix.registryUrl }} --access=${{ matrix.access }} --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Publish to GitHub registry if not already published
      - name: Publish package (GitHub)
        if: env.published == 'false' && matrix.registryName == 'github'
        run: |
          echo "Publishing to ${{ matrix.registryName }}..."
          npm publish --registry=${{ matrix.registryUrl }} --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
